name: Main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build package
      if: steps.check-setup-py.outputs.changed == 'true'
      run: |
        pip install setuptools wheel twine
        python setup.py sdist bdist_wheel

    - name: Publish package to PyPI
      if: steps.check-setup-py.outputs.changed == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        packages-dir: python/dist/
